"use client";
import { useCallback, useEffect, useState } from "react";
import { DEFAULTS, SAMPLE } from "@/config/app.config";
import { requestRoast } from "@/lib/api";
import type { LanguageId, ReportState, RoastLevel, RoastResult } from "@/types/roast";
import { TopBar } from "./TopBar"; import { RoastControls } from "./RoastControls"; import { ErrorMessageInput } from "./ErrorMessageInput"; import { CodeEditor } from "./CodeEditor"; import { RoastReport } from "./RoastReport"; import { StatusBar } from "./StatusBar";
export function Workspace() { const [roastLevel, setRoastLevel] = useState<RoastLevel>(DEFAULTS.roastLevel); const [language, setLanguage] = useState<LanguageId>(DEFAULTS.language); const [code, setCode] = useState(""); const [errorMessage, setErrorMessage] = useState(""); const [errorDrawerOpen, setErrorDrawerOpen] = useState(false); const [reportState, setReportState] = useState<ReportState>("empty"); const [roastResult, setRoastResult] = useState<RoastResult | null>(null); const [roastedCode, setRoastedCode] = useState(""); const [apiError, setApiError] = useState(""); const isRoasting = reportState === "loading";
const handleRoast = useCallback(async () => { if (isRoasting) return; if (!code.trim()) { setApiError("No code provided. I can't roast the void."); setReportState("error"); return; } setReportState("loading"); setRoastResult(null); setApiError(""); try { const result = await requestRoast({ language, code, roastLevel, errorMessage }); setRoastResult(result); setRoastedCode(code); setReportState("results"); } catch (error) { setApiError(error instanceof Error ? error.message : "Analysis failed."); setReportState("error"); } }, [code, errorMessage, isRoasting, language, roastLevel]);
useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") { event.preventDefault(); handleRoast(); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [handleRoast]); const errorLine = reportState === "results" && code === roastedCode ? roastResult?.issues[0]?.line : undefined;
return <main className="workstation"><TopBar><RoastControls roastLevel={roastLevel} onRoastLevelChange={setRoastLevel} language={language} onLanguageChange={setLanguage} onRoast={handleRoast} isRoasting={isRoasting} errorDrawerOpen={errorDrawerOpen} onToggleErrorDrawer={() => setErrorDrawerOpen(x => !x)} /></TopBar>{errorDrawerOpen && <ErrorMessageInput value={errorMessage} onChange={setErrorMessage} onClose={() => setErrorDrawerOpen(false)} />}<div className="workspace-body"><CodeEditor code={code} onChange={setCode} language={language} errorLine={errorLine} onLoadSample={() => { setLanguage(SAMPLE.language); setCode(SAMPLE.code); }} /><RoastReport state={reportState} roastLevel={roastLevel} language={language} result={roastResult} errorMsg={apiError} onRetry={handleRoast} onApplyFix={setCode} /></div><StatusBar isRoasting={isRoasting} /></main>; }
