import "server-only";
import { GoogleGenAI } from "@google/genai";
import { AI } from "@/config/app.config";
import { buildUserPrompt, ROAST_SYSTEM_INSTRUCTION } from "@/lib/prompt";
import { roastResponseSchema } from "@/lib/schema";
import type { RoastRequest, RoastResult } from "@/types/roast";
const pause = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
function friendlyErrorMessage(status: number | undefined) { if (status === 400) return "Gemini rejected this request. Please check the input."; if (status === 403) return "Gemini access was denied. Check GEMINI_API_KEY in .env.local."; if (status === 404) return `Model ${AI.model} was not found. Update it in config/app.config.ts.`; if (status === 429) return "Gemini rate limit reached. Please wait and retry."; if (status === 503) return "Gemini is temporarily overloaded. Please retry shortly."; return "Analysis failed. Check your Gemini configuration and try again."; }
export async function analyzeCode(request: RoastRequest): Promise<RoastResult> { const apiKey = process.env.GEMINI_API_KEY; if (!apiKey) throw new Error("GEMINI_API_KEY is missing. Copy .env.example to .env.local, add your key, and restart the server."); const ai = new GoogleGenAI({ apiKey }); let lastError: unknown; for (let attempt = 1; attempt <= AI.maxAttempts; attempt++) { try { const response = await ai.models.generateContent({ model: AI.model, contents: buildUserPrompt(request), config: { systemInstruction: ROAST_SYSTEM_INSTRUCTION, responseMimeType: "application/json", responseSchema: roastResponseSchema } }); if (!response.text) throw new Error("Gemini returned an empty response."); let result: Partial<RoastResult>; try { result = JSON.parse(response.text); } catch { throw new Error("Gemini returned invalid JSON. Please retry."); } return { roast: result.roast ?? "", issues: Array.isArray(result.issues) ? result.issues : [], correctedCode: result.correctedCode ?? "", takeaway: result.takeaway ?? "" }; } catch (error) { lastError = error; const status = (error as { status?: number }).status; if (status === 503 && attempt < AI.maxAttempts) { await pause(attempt * 1000); continue; } throw new Error(friendlyErrorMessage(status)); } } throw lastError instanceof Error ? lastError : new Error("Analysis failed."); }
